HET/HET/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authorization.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('categories/', include('categories.urls', namespace='categories'))
]

HET/authorization/urls.py
from django.contrib.auth.views import LogoutView, LoginView, PasswordResetView, PasswordResetDoneView, \
    PasswordChangeView, PasswordChangeDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from . import views

app_name = 'authorization'

urlpatterns = [
    path(
      'logout/',
      LogoutView.as_view(template_name='authorization/logged_out.html'),
      name='logout'
    ),
    path(
        'signup/',
        views.SignUp.as_view(template_name='authorization/signup.html'),
        name='signup'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='authorization/login.html'),
        name='login'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(template_name='authorization/password_reset_form.html'),
        name='password_reset_form'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(template_name='authorization/password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(template_name='authorization/password_change_form.html'),
        name='password_change'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(template_name='authorization/password_change_done.html'),
        name='password_change_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(template_name='authorization/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(template_name='authorization/password_reset_complete.html'),
        name='password_reset_complete'
    )
]

HET/categories/urls.py
from django.urls import path
from . import views

app_name = 'categories'

urlpatterns = [
    path('form/', views.categories_form, name='categories_form'),
    path('category_list', views.category_list, name='category_list')
]

HET/categories/models.py
from django.db import models


class Categories(models.Model):
    RASHODY = 'Расходы'
    DOHODY = 'Доходы'
    SECTION_CHOICES = [
        (RASHODY, 'Расходы'),
        (DOHODY, 'Доходы'),
    ]

    section = models.CharField(max_length=10, choices=SECTION_CHOICES, default=RASHODY)
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

HET/authorization/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django import forms

User = get_user_model()


class CreationForm(UserCreationForm):
    password1 = forms.CharField(
        label='Пароль',
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
        help_text='''
                    Ваш пароль не должен быть слишком простым.
                    Пароль должен содержать более 8 символов.
                    Пароль не может состоять только из цифр.
                    Пароль не должен повторять другие ваши пароли.
                ''',
    )
    password2 = forms.CharField(
        label='Повторите пароль',
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
        help_text='Повторите пароль',
    )

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
            'username': 'Имя пользователя',
            'email': 'Электронная почта',
        }
        help_texts = {
            'first_name': 'Введите ваше имя.',
            'last_name': 'Введите вашу фамилию.',
            'username': 'Введите ваше имя пользователя.',
            'email': 'Введите вашу электронную почту.',
        }

HET/categories/forms.py
from django import forms
from .models import Categories


class CategoriesForm(forms.ModelForm):
    class Meta:
        model = Categories
        fields = ['section', 'name']
        labels = {
            'section': 'Раздел',
            'name': 'Название',
        }

HET/authorization/views.py
from django.views.generic import CreateView

from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm

    success_url = reverse_lazy('posts:index')
    template_name = 'authorization/signup.html'

HET/categories/views.py
from django.shortcuts import render, redirect
from .forms import CategoriesForm
from src.o import Controller


def categories_form(request):
    if request.method == 'POST':
        form = CategoriesForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('categories_form')
    else:
        form = CategoriesForm()

    return render(request, 'categories/categories_form.html', {'form': form})


def category_list(request):
    dod = Controller()
    context = dod.render_categories_page(request)

    return render(request,'o.html', context)

HET/templates/authorization/logged_out.html
{% extends 'base.html' %}
{%  load static %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %} 

HET/templates/authorization/login.html
{% extends "base.html" %}
{%  load static %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <!-- Тест на внимательность. Без переопределения шаблона этого адреса
            не существует. Нужно что-то делать, иначе все упадет -->
            <a href="{% url 'password_reset' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

HET/templates/authorization/password_change_done.html
{% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Пароль изменён</title>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="../posts/index.html">
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
          </a>
        </div>
      </nav>
    </header>
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Пароль изменён
              </div>
              <div class="card-body">
                <p>Пароль изменён успешно</p>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
      </div>
    </main>
	  <footer class="border-top text-center py-3">
      <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
    </footer>
  </body>

HET/templates/authorization/password_change_form.html
{% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Изменение пароля</title>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="">
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
          </a>
        </div>
      </nav>
    </header>
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Изменить пароль
              </div>
              <div class="card-body">
                <form method="post" action="../users/password_change_form.html">
                  {% csrf_token %}
                  <div class="form-group row my-3 p-3">
                    <label for="id_old_password">
                      Старый пароль
                      <span class="required text-danger">*</span>
                    </label>
                    <input type="password" name="old_password" autofocus class="form-control" required id="id_old_password">
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password1">
                      Новый пароль
                      <span class="required text-danger">*</span>
                    </label>
                    <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
                      <small id="id_new_password1-help" class="form-text text-muted">
                        <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                      </small>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password2">
                      Подтверждение нового пароля
                      <span class="required text-danger">*</span>
                    </label>
                    <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Изменить пароль
                    </button>
                  </div>
                </form>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
      </div>
    </main>
	  <footer class="border-top text-center py-3">
      <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
    </footer>
  </body>

HET/templates/authorization/password_reset_complete.html
{% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Сброс пароля прошёл успешно</title>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="">
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
          </a>
        </div>
      </nav>
    </header>
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Восстановление пароля завершено
              </div>
              <div class="card-body">
                <p>Ваш пароль был сохранен. Используйте его для входа</p>
                <a href="../users/login.html">войти</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
	  <footer class="border-top text-center py-3">
      <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
    </footer>
  </body>

HET/templates/authorization/password_reset_confirm.html
{% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Новый пароль</title>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="">
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
          </a>
        </div>
      </nav>
    </header>
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Введите новый пароль
              </div>
              <div class="card-body">
                {% if validlink %}
                  <form method="post" action="{% url 'users:password_reset_confirm' %}">
                    {% csrf_token %}
                    <div class="form-group row my-3 p-3">
                      <label for="id_new_password1">
                        Новый пароль
                        <span class="required text-danger">*</span>
                      </label>
                      <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
                      <small id="id_new_password1-help" class="form-text text-muted">
                        <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                      </small>
                    </div>
                    <div class="form-group row my-3 p-3">
                      <label for="id_new_password2">
                        Подтверждение нового пароля
                        <span class="required text-danger">*</span>
                      </label>
                      <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
                    </div>
                    <div class="col-md-6 offset-md-4">
                      <button type="submit" class="btn btn-primary">
                        Назначить новый пароль
                      </button>
                    </div>
                  </form>
                {% else %}
                    <div class="row justify-content-center">
                      <div class="col-md-8 p-5">
                        <div class="card">
                          <div class="card-header">Ошибка</div>
                          <div class="card-body">
                            <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
                          </div> <!-- card body -->
                        </div> <!-- card -->
                      </div> <!-- col -->
                    </div> <!-- row -->
                {% endif %}
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
      </div>
    </main>
	  <footer class="border-top text-center py-3">
      <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
    </footer>
  </body>

HET/templates/authorization/password_reset_done.html
{% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Сброс пароля прошёл успешно</title>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="">
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
          </a>
        </div>
      </nav>
    </header>
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Отправлено письмо
              </div>
              <div class="card-body">
                <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
	  <footer class="border-top text-center py-3">
      <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
    </footer>
  </body>

HET/templates/authorization/password_reset_form.html
{% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Сброс пароля</title>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="">
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
          </a>
        </div>
      </nav>
    </header>
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
              </div>
              <div class="card-body">
                <form method="post" action="{% url 'users:password_reset_form' %}">
                  {% csrf_token %}
                  <div class="form-group row my-3 p-3">
                    <label for="id_email">
                      Адрес электронной почты
                      <span class="required text-danger">*</span>
                    </label>
                    <input type="email" name="email" maxlength="254" class="form-control" required id="id_email">
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Сбросить пароль
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
	  <footer class="border-top text-center py-3">
      <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
    </footer>
  </body>

HET/templates/authorization/signup.html
{% extends "base.html" %}
{%  load static %}
{% block title %}Регистрация{% endblock %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/base.css' %}">
<div class="signup_form">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %}
              {% if form.errors %}
                  {% for field in form %}
                    {% for error in field.errors %}
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <form method="post" action="{% url 'authorization:signup' %}">
              {% csrf_token %}

              {# Выводим поля в цикле, по отдельности #}
              {% for field in form %}
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {# К полю ввода добавляем атрибут class #}
                  {{ field|addclass:'form-control' }}
                    {% if field.help_text %}
                      <small
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
</div>
{% endblock %}

HET/templates/base.html
<!DOCTYPE html>
<html lang="en">
{%  load static %}
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      {% block content %}
        Контент не подвезли :(
      {% endblock %}
    </main>
    <footer>
      {% include 'includes/footer.html' %}
    </footer>
  </body>
</html>

HET/templates/categories/categories_form.html
{% extends 'base.html' %}
{%  load static %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
<form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</div> <!-- row -->
{% endblock %}

HET/templates/includes/article.html
<article>
    {% include 'includes/ul.html' %}
    {% include 'includes/p.html' %}
    <a href="{% url 'posts:group_posts' slug=slug %}">все мысли этого руса</a>
</article>

HET/templates/includes/footer.html
<footer class="border-top text-center py-3">
    <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
</footer>

HET/templates/includes/header.html
{% load static %}
<header>
  <style>
      @font-face {
        font-family: 'het';
        src: url('static/font/Comfortaa-Medium.ttf') format('truetype');
        font-weight: normal;
        font-style: normal;
      }

      .custom-font {
        color: #FFEFCD;
        font-family: 'het';
        font-size: 20px;
        text-decoration: underline;
      }

      .nav-link {
        color: #424530;
        font-size: 20px;
        text-decoration: underline;

      }

      .nav-link:hover,
      .nav-link.active {
          color: #FFEFCD;
      }
  </style>
  <nav class="navbar" style="background-color: #E09132">
    <div class="container">
      <a class="navbar-brand" href=" ">
        <img src="{% static 'imgs/hetik.png' %}" width="40" height="40" class="d-inline-block align-center" alt="">
        <span class="custom-font align-middle">Твой финансовый помощник</span>
      </a>
      <ul class="nav">
        {% with request.resolver_match.view_name as view_name %}
        {% if user.is_authenticated %}
        <li class="nav-item ">
          <a class="nav-link" href=" ">Новая запись</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light {% if view_name  == 'authorization:password_change' %}active{% endif %}" href="{% url 'authorization:password_change' %}">Изменить пароль</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light {% if view_name  == 'authorization:logout' %}active{% endif %}" href="{% url 'authorization:logout' %}">Выйти</a>
        </li>
        <li>
          Пользователь: {{ user.username }}
        </li>
        {% else %}
        <li class="nav-item custom-font">
          <a class="nav-link link-light {% if view_name  == 'authorization:login' %}active{% endif %}" href="{% url 'authorization:login' %}">Войти</a>
        </li>
        <li class="nav-item custom-font">
          <a class="nav-link link-light {% if view_name  == 'authorization:signup' %}active{% endif %}" href="{% url 'authorization:signup' %}">Регистрация</a>
        </li>
        {% endif %}
        {% endwith %}
      </ul>
    </div>
  </nav>
</header>


      {% comment %}
      Меню - список пунктов со стандартными классами Bootsrap.
      Класс nav-pills нужен для выделения активных пунктов
      {% endcomment %}

HET/templates/includes/p.html
<p>
    {{ p }}
</p>

HET/templates/includes/title.html
<title>{{ title }}</title>

HET/templates/includes/ul.html
<ul>
    {% for li in li %}
        <li>{{ li }}</li>
    {% endfor %}
</ul>

HET/templates/o.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Контроллер</title>
</head>
<body>
 {{ categories }}
</body>
</html>